---
languages: [fr_FR, en_US, es_ES, de_DE]
baseurl: "/"
url: "https://vegeta0911.github.io" # the base hostname & protocol for your site
sass:
  sass_dir: css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - vendor
plugins:
  - jekyll-seo-tag
title: "Documentations des plugins de Vegeta0911"
description: "Ceci est la documentation des plugins créés par Vegeta0911 de la solution domotique Jeedom."
author: "Vegeta0911"
image: https://doc.jeedom.com/images/logo.png
community: https://community.jeedom.com
market: https://market.jeedom.com
blog: https://blog.jeedom.com
doc: https://doc.jeedom.com
img: "images"
url_git: "https://github.com/vegeta0911"
paypal:
  name: "paypal.me/Vegeta0911"
  url2: "https://www.paypal.com/donate/?hosted_button_id=4SZ67QSJ35H2E"
  url: "https://www.paypal.com/donate/?hosted_button_id=4SZ67QSJ35H2E"
